### ISSUE TITLE
Update "CDC Guidance: All Data"

### ISSUE THREAD

**Issue by rypan** [usdigitalresponse/covid-exit-strategy#24]
To create/power the roll-up on how each state is doing on the 5 categories that we can calculate....

- State
- Category 1 - Yes/No
- Category 1 - # of Days
- Category 2 - Yes/No
- Category 2 - # of Days
- Category 3 - Yes/No
- Category 3 - # of Days
- Category 5 - Yes/No
- Category 5 - # of Days
- Category 6 - Yes/No
- Category 6 - # of Days

**Comment by lucasmbrown** [comment]
Got it. Are you looking for a Google Sheet that contains basically just those fields, and doesn't really need any additional fields? If so we can probably knock that out pretty quickly.

**Comment by rypan** [comment]
Yep! I don't think there is room for the other fields...

**Comment by lucasmbrown** [comment]
Great, thanks!

**Comment by patricksheehan** [comment]
@lucasmbrown is this completed?
