### ISSUE TITLE
Develop a social media strategy?

### ISSUE THREAD

**Issue by Freyert** [usdigitalresponse/covid-exit-strategy#34]
Hey all,

First off, I love what you're doing and the site is _awesome_. I do think including a social media strategy could be wildly effective. I've been following COVID19 on reddit obsessively since around February or March, and I only came across your site a few days ago.

I think the gate criteria is vitally important and could fit well inside the image size constraints of platforms like Instagram, Facebook, Reddit, etc. I've been trying to develop something myself, but all my attempts are fairly clumsy since data visualization is not my background.

As an example, someone regularly posts into the [r/bullcity subreddit](https://www.reddit.com/r/bullcity/comments/ho2ycv/durham_co_covid19_case_count_update_for_jul_8_11/) an infographic comparing the county wide increase from the last two weeks to the two weeks before.

![image](https://user-images.githubusercontent.com/449155/87255120-fd59b380-c455-11ea-943a-25963785f4d1.png)

The posts generally have high interaction rates.

I built a rudimentary pipeline https://github.com/Freyert/reddit_covid, but the visualization aspect eludes me. If you all are interested I would love to help build/manage a pipeline for publishing an infographic to various social media platforms on a regular basis.

**Comment by patricksheehan** [comment]
Hio! Thanks for the interest. So far we're focused on getting the data out there. Currently we're working on county-level data and visualization.

Having an automated pipeline to distribute this info sounds great. What would you need from us to implement? Our main site is in DataWrapper which is where all of our visualization lives.

**Comment by Freyert** [comment]
@patricksheehan really it just comes down to figuring out how to arrange the data on an image with the same dimensions as above.

I haven't used DataWrapper before, but just quickly checking it looks like I can get PNG's of the different chart features you publish. I could layer/organize those onto a social media image template and then post them I think.

Do you know of a way I could get a high resolution PNG export of each table element? Or maybe even just a high resolution image of each row? Then I could slice the elements up to fit into a reddit/facebook/instagram sized image?

It really comes down to I'm not good at making things pretty :) I can pull your data, but getting a pretty looking graph or gauge is not my expertise. Maybe I can find something reusable somewhere. I'll look into that.

**Comment by patricksheehan** [comment]
@Freyert yeah I think that makes sense. With the published site there may be an easy way to just query an image for each state? Because everything is baked into data wrapper we don't have static resources and we probably won't have time to develop that as a feature realistically.
