### ISSUE TITLE
New data sheet for policy vs trend charts

### ISSUE THREAD

**Issue by devinhunt** [usdigitalresponse/covid-exit-strategy#36]
To allow the charting of state-wide policy against the data, we need to generate a new data source (gdoc spreadsheet) which contains the follow time series:

1. Raw cases per million 
2. Spline cases per million 
3. Positivity

over the last 90 days. This could be inserted into the current "main site" sheet, but I would recommend a new one for organization.

**Comment by devinhunt** [comment]
Hey @smacpher. Would it be possible to make the following enhancements to this data set: 

1. Add a canonical date row in ISO formatting (2020-07-28)
2. Full data from Feb 1st
3. Simplify the row titles (removing Policy vs. Trend would be sufficient)

(For my own reference, [the current data set is here](https://docs.google.com/spreadsheets/d/1gRexnz4AJAIYJ6c5fQXR6ps2EDs7JPHu-CU7-5qE3EI/edit#gid=1444775127))

**Comment by smacpher** [comment]
Hey @devinhunt,

Yes definitely! For 2. do you want that as lags (eg. `T-n days all the way back to Feb 1st`) or just as rows (eg. identified by state and date)?

**Comment by devinhunt** [comment]
Ok! As per our call just now, let's use this format for the column titles: 

`cases-per-million-raw-[ISO DATE]`
`cases-per-million-3dcs-[ISO DATE]`
`positivity-3dcs-[ISO DATE]`


where `ISO DATE` is `2020-08-05` for example. Otherwise I think the current format works. I can group into time series client side for now.

**Comment by smacpher** [comment]
@devinhunt The spreadsheet is updated with these changes – let me know if there are any other updates you want made to it.

It also looks like most states don't have data before early March.

**Comment by devinhunt** [comment]
I'm integrating this into the demo now, looks pretty straight forward. One change I would make is to truncate the data set to Feb 1st 2020 to shrink limit the blank data. 

BTW, love the date column, that makes parsing much easier.
