### ISSUE TITLE
Calculate streak of how long we've been meeting each CDC criteria

### ISSUE THREAD

**Issue by lucasmbrown** [usdigitalresponse/covid-exit-strategy#6]
E.g., 1A has been TRUE for 14 days, or FALSE for 9 days, etc.

**Comment by smacpher** [comment]
- Every state for every date will have a boolean denoting whether they are meeting the CDC criteria for that date.
- Calculate the max run for most recent dates.
- Start with criteria 1A first to sanity check it.
- Also calculate the streak for failing.
- Add the fields I create to the criteria columns to make sure they get into their individual criteria sheets.
- Coordinate with Ryan on output format.
